name: "datree"
version: "0.1.165"
usage: "Validate Helm charts"
description: |-
  "Run Helm charts against the datree policy"
command: "$HELM_PLUGIN_DIR/scripts/run.sh"

hooks:
  install: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
  update: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"

useTunnel: false
ignoreFlags: false
